print("My", "name", "is", "AkHiL", "dodda.", sep="-")
print("My", "name", "is", sep="_", end="*")
print("AkHiL", "dodda.", sep="*", end="*\n")
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
